package by.rekuts.travelagency.view.configuration

import org.springframework.security.web.context.AbstractSecurityWebApplicationInitializer

class SecurityWebInitializer extends AbstractSecurityWebApplicationInitializer
